### PR TITLE
Allow to exclude from the testing files with an invalid extension by using the "excluded_exts" argument with a comma-separated list of excluded extensions.

### PR DESCRIPTION
**Pull request by kmgalanakis**
By using the `--excluded_ext=js` for example you are omitting the JS files from the test.

### CODE REVIEW

**Comment by zaantar** [comment]
Looks good @kmgalanakis but maybe it would be also worth it to exclude JS files in the Toolset ruleset (`standards/Toolset/ruleset.xml`), what do you think?

**Comment by kmgalanakis** [comment]
Honestly, I don't know how to do this, but in any case, I think this is not needed. With my changes we are offering the option for the user to skip JS files from the check but what happens for those users that don't want that? By leaving this as is we could make the script execution much more configurable.
What do you think?

**Comment by zaantar** [comment]
I agree, this is good as it is now for the general usage.

I'm going to adjust the rules for Toolset anyway, though, so that the ruleset contains the whole configuration of how we want this tool to behave, instead of having to remember about adding an additional commandline argument.

**Review by zaantar — COMMENTED** [review]
:+1:

**Pull request merged**
